server:
  port: 7777
  debug: true
  db_debug: true
  log_level: debug # debug\panic\fatal\error\warn\warning\info\trace
  log_filename: "./frontend.log"
  sync_period: "@every 5m"
backend:
  host: "http://127.0.0.1:7778"
  pure_host: "http://ms-loadrtst035:8888"
  test_starter: "http://172.17.155.33:9999"